--SET HEA ON LIN 270 PAGES 60 TAB ON FEED ON ECHO OFF VER ON TRIMS OFF TRIM ON TI OFF TIMI OFF LONG 24000 LONGC 240 SERVEROUT OFF;
SET TERM OFF;
@"/tmp/cs_store_set.sql"
CLEAR BREAK COLUMNS COMPUTE;
SET TERM ON;
--
