WHENEVER SQLERROR CONTINUE;
SET TERM OFF;
STORE SET "/tmp/cs_store_set.sql" REP;
SET TERM ON;
SET HEA ON LIN 2490 PAGES 100 TAB OFF FEED OFF ECHO OFF VER OFF TRIMS ON TRIM ON TI OFF TIMI OFF LONG 240000 LONGC 2400 NUM 20 SERVEROUT OFF;
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD"T"HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD"T"HH24:MI:SS.FF6';
ALTER SESSION SET STATISTICS_LEVEL = 'ALL';
ALTER SESSION SET "_px_cdb_view_enabled" = FALSE;
--