GRANT INHERIT PRIVILEGES ON USER sys TO &&1.;
GRANT EXECUTE ON DBMS_AUTO_SQLTUNE TO &&1. CONTAINER=ALL;
GRANT EXECUTE ON DBMS_AUTO_TASK_ADMIN TO &&1. CONTAINER=ALL;
GRANT EXECUTE ON DBMS_SCHEDULER TO &&1. CONTAINER=ALL;
GRANT ADVISOR TO &&1. CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO &&1. CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO &&1. CONTAINER=ALL;
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO &&1. CONTAINER=ALL;
GRANT ADMINISTER ANY SQL TUNING SET TO &&1. CONTAINER=ALL;
