ALTER SESSION SET container = CDB$ROOT;
--
UNDEF 1 2 3 4 5 6 7 8 9;
SET TERM ON HEA ON LIN 80 PAGES 14 TAB ON FEED ON ECHO OFF VER ON TRIMS OFF TRIM ON TI OFF TIMI OFF LONG 80 LONGC 80 SERVEROUT OFF;
CLEAR BREAK COLUMNS COMPUTE;
--