PRO
SET ECHO ON;
PRO
PRO ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PRO
PRO PDB: FLAMINGO_CTL
PRO
PRO FLAMINGO_CTL KIEVUSER WORK_REQUEST_BUCKET_V2 WORK_REQUEST_BUCKET_V2Idx2 DEPRECATE INDEX VISIBLE FAT:NO RENAME_AS (REQUESTSTATE, FINISHEDAT, PARTITIONKEY, ID, KIEVTXNID)
PRO
ALTER SESSION SET CONTAINER = FLAMINGO_CTL;
ALTER SESSION SET DDL_LOCK_TIMEOUT = 10;
SET ECHO ON;
PAUSE hit "return" to continue
ALTER INDEX KIEVUSER.WORK_REQUEST_BUCKET_V2Idx2 INVISIBLE;
ALTER INDEX KIEVUSER.WORK_REQUEST_BUCKET_V2Idx2 RENAME TO WORK_REQUEST_BUCKET_V2Idx2_;
PRO
PRO
PRO FLAMINGO_CTL KIEVUSER WORK_REQUEST_BUCKET_V2 WORK_REQUEST_BUCKET_V2IDX5 RENAME INDEX VISIBLE FAT:NO WORK_REQUEST_BUCKET_V2Idx2 (FINISHEDAT, ID, KIEVTXNID, PARTITIONKEY, REQUESTSTATE)
PRO
PRO sleep for 5 seconds...
EXEC DBMS_LOCK.sleep(5);
ALTER INDEX KIEVUSER.WORK_REQUEST_BUCKET_V2IDX5 RENAME TO WORK_REQUEST_BUCKET_V2Idx2;
PRO
PRO ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PRO
PRO PDB: VCN
PRO
PRO VCN VCNAD2R1 mapUpdates_AD SEQ_NUM_TO_UPD_NDX DEPRECATE INDEX VISIBLE FAT:NO RENAME_AS (KIEVTXNID, SEQUENCETIMESTAMP, VCNID, MAPPINGKIND, ENTITYID, UPDATETIMESTAMP)
PRO
ALTER SESSION SET CONTAINER = VCN;
ALTER SESSION SET DDL_LOCK_TIMEOUT = 10;
SET ECHO ON;
PAUSE hit "return" to continue
ALTER INDEX VCNAD2R1.SEQ_NUM_TO_UPD_NDX INVISIBLE;
ALTER INDEX VCNAD2R1.SEQ_NUM_TO_UPD_NDX RENAME TO SEQ_NUM_TO_UPD_NDX_;
PRO
PRO
PRO VCN VCNAD2R1 MAPUPDATES_AD MAPUPDATES_AD_IX2 RENAME INDEX VISIBLE FAT:NO SEQ_NUM_TO_UPD_NDX (ENTITYID, KIEVTXNID, MAPPINGKIND, SEQUENCETIMESTAMP, UPDATETIMESTAMP, VCNID)
PRO
PRO sleep for 5 seconds...
EXEC DBMS_LOCK.sleep(5);
ALTER INDEX VCNAD2R1.MAPUPDATES_AD_IX2 RENAME TO SEQ_NUM_TO_UPD_NDX;
PRO
QUIT;
PRO