SET TERM ON HEA ON LIN 2490 PAGES 100 TAB OFF FEED OFF ECHO OFF VER OFF TRIMS ON TRIM ON TI OFF TIMI OFF LONG 240000 LONGC 2400 NUM 20 SERVEROUT OFF;
COL PDB_NAME FOR A30;
COL OWNER FOR A30;
COL TABLE_NAME FOR A30;
COL NUM_ROWS FOR 999,999,990;
COL SIZE_GB FOR 999,990.0;
SPO /tmp/gc_gt_20k.txt
SELECT REALM, REGION_ACRONYM, LOCALE, PDB_NAME, OWNER, TABLE_NAME, NUM_ROWS, ROUND(BLOCKS * 8 * 1024 / POWER(10, 9), 1) AS SIZE_GB, DB_NAME, GC_STATUS, HOST_NAME
FROM c##iod.gc_gt_20k
WHERE TABLE_NAME IN ('WORKLOG_TOMBSTONES', 'VOLUMES_TOMBSTONES', 'ATTACHMENTS_HISTORY', 'ACCEPTED_REQUESTS', 'VOL_RECLAIM_AUDIT', 'BACKUPS_TOMBSTONES', 'BACKUP_BOOTVOLMETA_TOMB', 'VOLGRP_BACKUPS_TOMBSTONE', 'BOOTVOLUMESMETADATA', 'IMG_WORKLOG_TOMBSTONES', 'BOOTVOLUME_TOMBSTONES', 'RETRYTOKENSNEW', 'BACKUPS', 'RQS', 'BACKUP_GBHOUR_METERING_V2')
-- AND version = TO_DATE('2021-04-30', 'YYYY-MM-DD')
AND version = TO_DATE('2021-08-16', 'YYYY-MM-DD')
ORDER BY REALM_ORDER_BY, REGION_ORDER_BY, LOCALE_ORDER_BY, PDB_NAME, OWNER, TABLE_NAME
/
SPO OFF;
