SET TERM ON HEA ON LIN 2490 PAGES 100 TAB OFF FEED OFF ECHO OFF VER OFF TRIMS ON TRIM ON TI OFF TIMI OFF LONG 240000 LONGC 2400 NUM 20 SERVEROUT OFF;
COL PDB_NAME FOR A30;
COL OWNER FOR A30;
COL TABLE_NAME FOR A30;
COL before_NUM_ROWS FOR 999,999,990;
COL before_SIZE_GB FOR 999,990.0;
COL after_NUM_ROWS FOR 999,999,990;
COL after_SIZE_GB FOR 999,990.0;
SPO /tmp/gc_gt_20k.txt
WITH
gc_gt_20k_before AS (
SELECT REALM, REGION_ACRONYM, LOCALE, PDB_NAME, OWNER, TABLE_NAME, NUM_ROWS, ROUND(BLOCKS * 8 * 1024 / POWER(10, 9), 1) AS SIZE_GB, DB_NAME, GC_STATUS, HOST_NAME, REALM_ORDER_BY, REGION_ORDER_BY, LOCALE_ORDER_BY
FROM c##iod.gc_gt_20k
WHERE TABLE_NAME IN ('WORKLOG_TOMBSTONES', 'VOLUMES_TOMBSTONES', 'ATTACHMENTS_HISTORY', 'ACCEPTED_REQUESTS', 'VOL_RECLAIM_AUDIT', 'BACKUPS_TOMBSTONES', 'BACKUP_BOOTVOLMETA_TOMB', 'VOLGRP_BACKUPS_TOMBSTONE', 'BOOTVOLUMESMETADATA', 'IMG_WORKLOG_TOMBSTONES', 'BOOTVOLUME_TOMBSTONES', 'RETRYTOKENSNEW', 'BACKUPS', 'RQS', 'BACKUP_GBHOUR_METERING_V2')
AND version = TO_DATE('2021-04-30', 'YYYY-MM-DD')
-- AND version = TO_DATE('2021-08-16', 'YYYY-MM-DD')
),
gc_gt_20k_after AS (
SELECT REALM, REGION_ACRONYM, LOCALE, PDB_NAME, OWNER, TABLE_NAME, NUM_ROWS, ROUND(BLOCKS * 8 * 1024 / POWER(10, 9), 1) AS SIZE_GB, DB_NAME, GC_STATUS, HOST_NAME, REALM_ORDER_BY, REGION_ORDER_BY, LOCALE_ORDER_BY
FROM c##iod.gc_gt_20k
WHERE TABLE_NAME IN ('WORKLOG_TOMBSTONES', 'VOLUMES_TOMBSTONES', 'ATTACHMENTS_HISTORY', 'ACCEPTED_REQUESTS', 'VOL_RECLAIM_AUDIT', 'BACKUPS_TOMBSTONES', 'BACKUP_BOOTVOLMETA_TOMB', 'VOLGRP_BACKUPS_TOMBSTONE', 'BOOTVOLUMESMETADATA', 'IMG_WORKLOG_TOMBSTONES', 'BOOTVOLUME_TOMBSTONES', 'RETRYTOKENSNEW', 'BACKUPS', 'RQS', 'BACKUP_GBHOUR_METERING_V2')
-- AND version = TO_DATE('2021-04-30', 'YYYY-MM-DD')
AND version = TO_DATE('2021-08-16', 'YYYY-MM-DD')
)
SELECT b.REALM, b.REGION_ACRONYM, b.LOCALE, b.PDB_NAME, b.OWNER, b.TABLE_NAME, b.NUM_ROWS AS before_NUM_ROWS, a.NUM_ROWS AS after_NUM_ROWS, b.SIZE_GB AS before_SIZE_GB, a.SIZE_GB AS after_SIZE_GB,  b.DB_NAME, b.HOST_NAME
  FROM gc_gt_20k_before b, gc_gt_20k_after a
WHERE a.REALM(+) = b.REALM AND a.REGION_ACRONYM(+) = b.REGION_ACRONYM AND a.LOCALE(+) = b.LOCALE AND a.PDB_NAME(+) = b.PDB_NAME AND a.OWNER(+) = b.OWNER AND a.TABLE_NAME(+) = b.TABLE_NAME
ORDER BY b.REALM_ORDER_BY, b.REGION_ORDER_BY, b.LOCALE_ORDER_BY, b.PDB_NAME, b.OWNER, b.TABLE_NAME
/
SPO OFF;
