SET HEA ON LIN 2490 PAGES 100 TAB OFF FEED OFF ECHO OFF VER OFF TRIMS ON TRIM ON TI OFF TIMI OFF LONG 240000 LONGC 2400 NUM 20 SERVEROUT OFF;
COL index_name FOR A30;
COL min_owner FOR A30;
COL max_owner FOR A30;
SELECT index_name, COUNT(*), MIN(owner) min_owner, MAX(owner) max_owner
  FROM dba_indexes
 WHERE table_name = 'KIEVTRANSACTIONS'
GROUP BY index_name
ORDER BY index_name
/
