SET TERM ON HEA ON LIN 2490 PAGES 100 TAB OFF FEED OFF ECHO OFF VER OFF TRIMS ON TRIM ON TI OFF TIMI OFF LONG 240000 LONGC 2400 NUM 20 SERVEROUT OFF;
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD"T"HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD"T"HH24:MI:SS.FF3';
--
WITH
run_details AS (
SELECT CAST(LAG(log_time) OVER(PARTITION BY log_name ORDER BY log_time) AS DATE) AS gap_begin,
       CAST(log_time AS DATE) AS gap_end,
       (CAST(log_time AS DATE) - CAST(LAG(log_time) OVER(PARTITION BY log_name ORDER BY log_time) AS DATE)) * 24 * 3600 AS seconds
  FROM C##IOD.iod_log_msg
 WHERE UPPER(log_name) LIKE '%IOD_SESS.MONITOR%'
   AND log_time > SYSDATE - 60/24/3600
 ORDER BY log_time
)
SELECT * 
  FROM run_details 
 WHERE gap_begin IS NOT NULL
ORDER BY 1 NULLS FIRST
/
