SET TERM ON HEA ON LIN 2490 PAGES 100 TAB OFF FEED OFF ECHO OFF VER OFF TRIMS ON TRIM ON TI OFF TIMI OFF LONG 240000 LONGC 2400 NUM 20 SERVEROUT OFF;
COL pdb_name FOR A30;
SELECT c.name AS pdb_name, COUNT(*) AS cursors, 
       SUM(CASE o.cursor_type WHEN 'SESSION CURSOR CACHED' THEN 1 ELSE 0 END) AS cached,
       SUM(CASE o.cursor_type WHEN 'OPEN' THEN 1 ELSE 0 END) AS open,
       SUM(CASE WHEN o.cursor_type IN ('DICTIONARY LOOKUP CURSOR CACHED', 'BUNDLE DICTIONARY LOOKUP CACHED') THEN 1 ELSE 0 END) AS dict,
       SUM(CASE o.cursor_type WHEN 'CONSTRAINTS CURSOR CACHED' THEN 1 ELSE 0 END) AS cons,
       SUM(CASE WHEN o.cursor_type NOT IN ('SESSION CURSOR CACHED', 'OPEN', 'DICTIONARY LOOKUP CURSOR CACHED', 'BUNDLE DICTIONARY LOOKUP CACHED', 'CONSTRAINTS CURSOR CACHED') THEN 1 ELSE 0 END) AS other,
       o.sid
  FROM v$open_cursor o, v$containers c
 WHERE o.con_id > 2
   AND c.con_id = o.con_id
 GROUP BY 
       c.name, o.sid
 HAVING COUNT(*) > 200
 ORDER BY
       1, 2 DESC
/