SET TERM ON HEA ON LIN 2490 PAGES 100 TAB OFF FEED OFF ECHO OFF VER OFF TRIMS ON TRIM ON TI OFF TIMI OFF LONG 240000 LONGC 2400 NUM 20 SERVEROUT OFF;
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD"T"HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD"T"HH24:MI:SS.FF3';
COL log_time FOR A23;
COL log_msg FOR A200;
SELECT log_time, log_msg
FROM C##IOD.iod_log_msg
WHERE log_msg LIKE '%new_utilization_limit%'
AND log_name = 'IOD_RSRC_MGR.THROTTLED_PDB_SENTINEL'
AND log_time > SYSDATE - 7
ORDER BY log_time
/
