SET TERM ON HEA ON LIN 2490 PAGES 100 TAB OFF FEED OFF ECHO OFF VER OFF TRIMS ON TRIM ON TI OFF TIMI OFF LONG 240000 LONGC 2400 NUM 20 SERVEROUT OFF;
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD"T"HH24:MI:SS';
COL severity FOR 000 HEA 'SEV';
COL pdb_name FOR A30 TRUNC;
COL alert_type FOR A10 TRUNC;
COL key_value FOR A200 TRUNC;
SELECT severity, snap_time, pdb_name, alert_type, key_value FROM C##IOD.alerts_hist_v ORDER BY 1, 2;