GRANT EXECUTE ON DBMS_LOCK TO &&1.;
GRANT SELECT_CATALOG_ROLE TO &&1. CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO &&1. CONTAINER=ALL;
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO &&1. CONTAINER=ALL;
GRANT ADMINISTER ANY SQL TUNING SET TO &&1. CONTAINER=ALL;
ALTER USER &&1. SET CONTAINER_DATA=ALL CONTAINER = CURRENT;
