GRANT INHERIT PRIVILEGES ON USER sys TO &&1.;
GRANT EXECUTE ON DBMS_LOCK TO &&1.;
GRANT SELECT_CATALOG_ROLE TO &&1. CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO &&1. CONTAINER=ALL;
GRANT SELECT ON sys.wri$_optstat_tab_history TO &&1. CONTAINER=ALL;