SET HEA ON LIN 500 PAGES 100 TAB OFF FEED OFF ECHO OFF VER OFF TRIMS ON TRIM ON TI OFF TIMI OFF;
SET SERVEROUT OFF;

PRO FORMAT: BASIC, TYPICAL, ALL, ADVANCED (default)
SELECT plan_table_output explain_plan FROM 
TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', NULL, NVL('&format.', 'ADVANCED')))
/
