SET LIN 300 PAGES 0 VER OFF FEED OFF ECHO OFF;
PRO FORMAT: BASIC, TYPICAL, ALL, ADVANCED (default)
SELECT plan_table_output explain_plan FROM 
TABLE(DBMS_XPLAN.DISPLAY('PLAN_TABLE', NULL, NVL('&format.', 'ADVANCED')))
/
